"""``aimemory.domain`` - the frozen contract layer of AI Memory V0.1.

Owned by A02 (Architecture & Contracts). **Frozen after P1**: every change needs an ADR
(``docs/development/agent-protocol.md``). Consumers: A04 (persistence), A05 (LLM provider),
A06 (embedding), A07a/A07b (ingestion), A08 (knowledge/temporal), A09 (retrieval/gateway),
A10 (MCP), A11/A16 (dashboards), A12 (tests).

Modules

``enums``        closed vocabularies (policies, statuses, stages, ontology labels, predicates)
``base``         shared pydantic configuration (``DomainModel`` / ``OpenModel``)
``provenance``   the ``[PROV]`` column set of plan section J and the explain chain step
``models``       one class per PostgreSQL table of plan section G plus ADR-0010/0011 tables
``extraction``   the Python mirror of ``schemas/extraction/*.json`` and ``ExtractionResult``
``retrieval``    Gateway request/response DTOs and the typed view of ``config/retrieval.yaml``
``source_uri``   ADR-0004 URI scheme and the plan section T ``path_guard``
``ports``        Protocols: ``LLMProvider``, ``EmbeddingProvider``, ``KnowledgeEngine``,
                 ``GraphStore``, ``TextExtractor``, ``Chunker``

Reference documents: ``docs/architecture/data-model.md``, ``ontology.md``, ``temporal.md``,
``retrieval.md``.
"""

from .base import DomainModel, OpenModel
from .enums import (
    ArtifactStatus,
    ArtifactType,
    ChangeType,
    DocKind,
    EngineKind,
    EntityType,
    EpisodeStatus,
    EpisodeType,
    FactStatus,
    JobStage,
    JobState,
    McpToolKind,
    ObjectType,
    Origin,
    Predicate,
    ProjectStatus,
    RelationshipGroup,
    RetrieverKind,
    ReviewVerdict,
    RunAction,
    RunRequestStatus,
    RunStatus,
    RunTrigger,
    SourceEventType,
    SourceKind,
    SourceStatus,
    SourceUriScheme,
    StatedArtifactStatus,
    StoragePolicy,
    Tier,
    Track,
    Trust,
)
from .extraction import (
    EPISODE_EXTRACTION_SCHEMA_ID,
    EXTRACTABLE_ARTIFACT_TYPES,
    EXTRACTABLE_ENTITY_TYPES,
    EXTRACTABLE_PREDICATES,
    RELATIONSHIP_EXTRACTION_SCHEMA_ID,
    EpisodeExtraction,
    ExtractedArtifact,
    ExtractedEntity,
    ExtractedFact,
    ExtractionResult,
    RelationshipExtraction,
)
from .models import (
    ArtifactEntity,
    Chunk,
    Device,
    Embedding,
    EmbeddingModel,
    Entity,
    EntityMention,
    Episode,
    ExtractionModel,
    ExtractionReview,
    Fact,
    IngestionJob,
    IngestionRun,
    KnowledgeArtifact,
    McpAuditLog,
    MetricsSnapshot,
    MirrorBlob,
    Project,
    ProjectAlias,
    RetrievalLog,
    RunRequest,
    ServiceStat,
    Source,
    SourceEvent,
    SourceFrontmatter,
    SourceRoot,
    SourceText,
    SourceVersion,
)
from .ports import (
    ChunkDraft,
    Chunker,
    EmbeddingProvider,
    EmbeddingResult,
    EpisodeContext,
    ExtractedText,
    GraphNode,
    GraphRelationship,
    GraphStore,
    KnowledgeEngine,
    LLMProvider,
    LLMResponse,
    TextExtractor,
    chunk_from_draft,
)
from .provenance import (
    DETERMINISTIC_MODEL_ID,
    PROVENANCE_COLUMNS,
    Provenance,
    ProvenanceChainStep,
)
from .retrieval import (
    AssembledContext,
    Candidate,
    ContextBlock,
    ExplainChain,
    RelatedEntity,
    RetrievalConfig,
    ScoredHit,
    SearchQuery,
    SearchResult,
)
from .source_uri import (
    SourceURI,
    build_source_uri,
    is_safe_relative_path,
    parse_source_uri,
    path_guard,
    safe_relative_path,
)

__all__ = [
    "DETERMINISTIC_MODEL_ID",
    "EPISODE_EXTRACTION_SCHEMA_ID",
    "EXTRACTABLE_ARTIFACT_TYPES",
    "EXTRACTABLE_ENTITY_TYPES",
    "EXTRACTABLE_PREDICATES",
    "PROVENANCE_COLUMNS",
    "RELATIONSHIP_EXTRACTION_SCHEMA_ID",
    "ArtifactEntity",
    "ArtifactStatus",
    "ArtifactType",
    "AssembledContext",
    "Candidate",
    "ChangeType",
    "Chunk",
    "ChunkDraft",
    "Chunker",
    "ContextBlock",
    "Device",
    "DocKind",
    "DomainModel",
    "Embedding",
    "EmbeddingModel",
    "EmbeddingProvider",
    "EmbeddingResult",
    "EngineKind",
    "Entity",
    "EntityMention",
    "EntityType",
    "Episode",
    "EpisodeContext",
    "EpisodeExtraction",
    "EpisodeStatus",
    "EpisodeType",
    "ExplainChain",
    "ExtractedArtifact",
    "ExtractedEntity",
    "ExtractedFact",
    "ExtractedText",
    "ExtractionModel",
    "ExtractionResult",
    "ExtractionReview",
    "Fact",
    "FactStatus",
    "GraphNode",
    "GraphRelationship",
    "GraphStore",
    "IngestionJob",
    "IngestionRun",
    "JobStage",
    "JobState",
    "KnowledgeArtifact",
    "KnowledgeEngine",
    "LLMProvider",
    "LLMResponse",
    "McpAuditLog",
    "McpToolKind",
    "MetricsSnapshot",
    "MirrorBlob",
    "ObjectType",
    "OpenModel",
    "Origin",
    "Predicate",
    "Project",
    "ProjectAlias",
    "ProjectStatus",
    "Provenance",
    "ProvenanceChainStep",
    "RelatedEntity",
    "RelationshipExtraction",
    "RelationshipGroup",
    "RetrievalConfig",
    "RetrievalLog",
    "RetrieverKind",
    "ReviewVerdict",
    "RunAction",
    "RunRequest",
    "RunRequestStatus",
    "RunStatus",
    "RunTrigger",
    "ScoredHit",
    "SearchQuery",
    "SearchResult",
    "ServiceStat",
    "Source",
    "SourceEvent",
    "SourceEventType",
    "SourceFrontmatter",
    "SourceKind",
    "SourceRoot",
    "SourceStatus",
    "SourceText",
    "SourceURI",
    "SourceUriScheme",
    "SourceVersion",
    "StatedArtifactStatus",
    "StoragePolicy",
    "TextExtractor",
    "Tier",
    "Track",
    "Trust",
    "build_source_uri",
    "chunk_from_draft",
    "is_safe_relative_path",
    "parse_source_uri",
    "path_guard",
    "safe_relative_path",
]
