"""0001_initial - every table of docs/architecture/data-model.md sections 1-4, the [PROV] columns
of section 6, the provenance_v view, and the Tier-0 registry seeds.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-14

Owner: A04 (P5-T01). Source of truth: docs/architecture/data-model.md, packages/aimemory/domain/
models.py, packages/aimemory/domain/enums.py, packages/aimemory/domain/provenance.py.

Table creation order respects every foreign key so no column needs a deferred/circular fix-up
except `sources.current_version_id`, which the spec explicitly calls out as added after
`source_versions` exists.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _exec(sql: str) -> None:
    op.execute(sa.text(sql))


# ------------------------------------------------------------------------------------------------
# CHECK constraint value lists, generated by hand from aimemory.domain.enums (frozen contract).
# ------------------------------------------------------------------------------------------------

STORAGE_POLICY = "('IGNORE','CATALOG_ONLY','INDEX_CONTENT','MIRROR')"
SOURCE_STATUS = "('active','deleted','moved')"
SOURCE_KIND = "('file','directory','repository','note')"
ORIGIN = "('internal','external')"
TRUST = "('high','medium','low')"
CHANGE_TYPE = "('new','modified','moved','deleted','unchanged','duplicate')"
JOB_STAGE = (
    "('discover','classify','fingerprint','diff','extract_metadata','extract_text','chunk',"
    "'embed','episode','extract_knowledge','validate','resolve_entities','temporal',"
    "'project_graph','provenance')"
)
JOB_STATE = "('pending','running','done','failed','skipped')"
EPISODE_TYPE = "('document','document_change','registry','manual','mcp')"
EPISODE_STATUS = "('pending','queued','running','extracted','failed','skipped')"
ENGINE_KIND = "('deterministic','native','graphiti')"
FACT_STATUS = "('current','historical','unconfirmed')"
ARTIFACT_TYPE = "('decision','requirement','task','finding','hypothesis','experiment','summary')"
ARTIFACT_STATUS = (
    "('current','superseded','historical','unconfirmed','proposed','done','abandoned')"
)
ENTITY_TYPE = (
    "('Project','SubProject','Person','Organization','Technology','Concept','Document',"
    "'Repository','Source','Device','Decision','Requirement','Task','Experiment','Dataset',"
    "'ResearchFinding','Episode','Application','InfrastructureComponent')"
)
TRACK = "('business','research','career','foundation')"
PROJECT_STATUS = "('active','paused','planned','completed','abandoned','unknown')"
OBJECT_TYPE = "('chunk','artifact','fact','entity','episode','source')"
SOURCE_EVENT_TYPE = (
    "('created','modified','moved','deleted','restored','policy_changed','secret_suspected',"
    "'rescanned')"
)
RUN_STATUS = "('pending','running','completed','failed','cancelled')"
RUN_TRIGGER = "('cli','ops_page','worker','schedule','test')"
PREDICATE = (
    "('PART_OF','BELONGS_TO','STORED_ON','HAS_SOURCE','MENTIONS','LINKS_TO','DERIVED_FROM',"
    "'USES','DEPENDS_ON','RELATED_TO','IMPLEMENTS','SUPPORTS','CONTRADICTS','PRODUCES',"
    "'REQUIRES','CREATED_BY','GENERATED_BY','SUPERSEDES','DECIDED_IN','HAS_STATUS','HAS_OWNER',"
    "'USES_ARCHITECTURE','DEPLOYED_ON','HAS_STAGE','SELECTED_OPTION')"
)
FUNCTIONAL_PREDICATES = (
    "('HAS_STATUS','HAS_OWNER','USES_ARCHITECTURE','DEPLOYED_ON','HAS_STAGE','SELECTED_OPTION')"
)
PROJECT_ALIAS_SOURCE = "('config','registry','extraction','manual')"
ARTIFACT_ENTITY_ROLE = "('about','mentions','produces','affects')"
MCP_KIND = "('read','write')"


def upgrade() -> None:
    # --------------------------------------------------------------------------------------
    # 1. Registries
    # --------------------------------------------------------------------------------------
    _exec(
        """
        CREATE TABLE devices (
            id          text PRIMARY KEY,
            label       text NOT NULL,
            os          text,
            notes       text,
            created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    _exec(
        f"""
        CREATE TABLE projects (
            id          text PRIMARY KEY,
            name        text NOT NULL,
            track       text NOT NULL CHECK (track IN {TRACK}),
            parent_id   text NULL REFERENCES projects(id),
            status      text NOT NULL DEFAULT 'unknown' CHECK (status IN {PROJECT_STATUS}),
            goal_ids    text[] NOT NULL DEFAULT '{{}}',
            summary     text,
            attributes  jsonb NOT NULL DEFAULT '{{}}',
            root_ids    text[] NOT NULL DEFAULT '{{}}',
            created_at  timestamptz NOT NULL DEFAULT now(),
            updated_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_projects_no_self_parent CHECK (parent_id <> id)
        )
        """
    )
    _exec("CREATE INDEX ix_projects_track ON projects (track)")
    _exec("CREATE INDEX ix_projects_parent ON projects (parent_id)")
    _exec("CREATE INDEX ix_projects_status ON projects (status)")

    _exec(
        f"""
        CREATE TABLE project_aliases (
            id                uuid PRIMARY KEY,
            project_id        text NOT NULL REFERENCES projects(id),
            alias             text NOT NULL,
            normalized_alias  text NOT NULL,
            source            text NOT NULL DEFAULT 'config' CHECK (source IN {PROJECT_ALIAS_SOURCE})
        )
        """
    )
    _exec(
        "CREATE UNIQUE INDEX uq_project_aliases_normalized ON project_aliases (normalized_alias)"
    )
    _exec("CREATE INDEX ix_project_aliases_project ON project_aliases (project_id)")

    _exec(
        f"""
        CREATE TABLE source_roots (
            root_id             text PRIMARY KEY,
            scheme              text NOT NULL CHECK (scheme IN ('vault','localfs','git')),
            label               text NOT NULL,
            container_path      text NOT NULL,
            device_id           text NOT NULL REFERENCES devices(id),
            enabled             boolean NOT NULL DEFAULT true,
            default_policy      text NOT NULL DEFAULT 'INDEX_CONTENT' CHECK (default_policy IN {STORAGE_POLICY}),
            default_project_id  text NULL REFERENCES projects(id),
            kind                text NOT NULL DEFAULT 'directory' CHECK (kind IN {SOURCE_KIND}),
            registry_role       text,
            priority_paths      text[] NOT NULL DEFAULT '{{}}',
            mirror_paths        text[] NOT NULL DEFAULT '{{}}',
            exclude_extra       text[] NOT NULL DEFAULT '{{}}',
            origin_overrides    jsonb NOT NULL DEFAULT '[]'
        )
        """
    )
    _exec("CREATE UNIQUE INDEX uq_source_roots_label ON source_roots (label)")

    _exec(
        """
        CREATE TABLE embedding_models (
            id          text PRIMARY KEY,
            name        text NOT NULL,
            dimension   int NOT NULL CHECK (dimension > 0),
            revision    text,
            normalized  boolean NOT NULL DEFAULT true,
            max_seq     int NOT NULL DEFAULT 256,
            created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec(
        "CREATE UNIQUE INDEX uq_embedding_models_name_revision ON embedding_models (name, revision)"
    )

    _exec(
        """
        CREATE TABLE extraction_models (
            id          text PRIMARY KEY,
            provider    text NOT NULL DEFAULT 'ollama',
            name        text NOT NULL,
            digest      text,
            parameters  jsonb NOT NULL DEFAULT '{}',
            created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    # --------------------------------------------------------------------------------------
    # 2a. Operations tables needed before sources/episodes can reference them
    # --------------------------------------------------------------------------------------
    _exec(
        f"""
        CREATE TABLE ingestion_runs (
            id            uuid PRIMARY KEY,
            root_id       text NULL REFERENCES source_roots(root_id),
            tier          smallint NOT NULL DEFAULT 2 CHECK (tier IN (0,1,2)),
            trigger       text NOT NULL DEFAULT 'cli' CHECK (trigger IN {RUN_TRIGGER}),
            requested_by  text,
            status        text NOT NULL DEFAULT 'pending' CHECK (status IN {RUN_STATUS}),
            started_at    timestamptz NOT NULL DEFAULT now(),
            finished_at   timestamptz,
            counters      jsonb NOT NULL DEFAULT '{{}}',
            error         text
        )
        """
    )
    _exec("CREATE INDEX ix_ingestion_runs_started ON ingestion_runs (started_at DESC)")

    # --------------------------------------------------------------------------------------
    # 2b. Sources and content
    # --------------------------------------------------------------------------------------
    _exec(
        f"""
        CREATE TABLE sources (
            id                  uuid PRIMARY KEY,
            uri                 text NOT NULL,
            root_id             text NOT NULL REFERENCES source_roots(root_id),
            relative_path       text NOT NULL,
            project_id          text NULL REFERENCES projects(id),
            kind                text NOT NULL DEFAULT 'file' CHECK (kind IN {SOURCE_KIND}),
            media_type          text,
            policy              text NOT NULL DEFAULT 'CATALOG_ONLY' CHECK (policy IN {STORAGE_POLICY}),
            policy_reason       text,
            status              text NOT NULL DEFAULT 'active' CHECK (status IN {SOURCE_STATUS}),
            moved_from_uri      text,
            current_version_id  uuid NULL,
            secret_suspected    boolean NOT NULL DEFAULT false,
            origin              text NOT NULL DEFAULT 'internal' CHECK (origin IN {ORIGIN}),
            trust               text NOT NULL DEFAULT 'high' CHECK (trust IN {TRUST}),
            first_seen_at       timestamptz NOT NULL DEFAULT now(),
            last_seen_at        timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec("CREATE UNIQUE INDEX uq_sources_uri ON sources (uri)")
    _exec("CREATE INDEX ix_sources_root_path ON sources (root_id, relative_path)")
    _exec("CREATE INDEX ix_sources_project ON sources (project_id)")
    _exec("CREATE INDEX ix_sources_status ON sources (status)")
    _exec("CREATE INDEX ix_sources_policy ON sources (policy) WHERE status = 'active'")
    _exec("CREATE INDEX ix_sources_secret ON sources (secret_suspected) WHERE secret_suspected")

    _exec(
        f"""
        CREATE TABLE source_versions (
            id                 uuid PRIMARY KEY,
            source_id          uuid NOT NULL REFERENCES sources(id),
            content_hash       text NOT NULL,
            size_bytes         bigint NOT NULL CHECK (size_bytes >= 0),
            mtime              timestamptz,
            git_commit         text,
            git_branch         text,
            observed_at        timestamptz NOT NULL,
            ingestion_run_id   uuid NULL REFERENCES ingestion_runs(id),
            is_current         boolean NOT NULL DEFAULT true,
            change_type        text NOT NULL DEFAULT 'new' CHECK (change_type IN {CHANGE_TYPE}),
            created_at         timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec("CREATE UNIQUE INDEX uq_source_versions_hash ON source_versions (source_id, content_hash)")
    _exec(
        "CREATE INDEX ix_source_versions_source_current ON source_versions (source_id, is_current) "
        "WHERE is_current"
    )
    _exec("CREATE INDEX ix_source_versions_hash ON source_versions (content_hash)")
    _exec("CREATE INDEX ix_source_versions_observed ON source_versions (observed_at DESC)")

    # sources.current_version_id can only be constrained once source_versions exists (data-model.md
    # §2: "FK added after source_versions exists (DEFERRABLE)").
    _exec(
        "ALTER TABLE sources ADD CONSTRAINT fk_sources_current_version "
        "FOREIGN KEY (current_version_id) REFERENCES source_versions(id) DEFERRABLE INITIALLY DEFERRED"
    )

    _exec(
        """
        CREATE TABLE source_text (
            version_id         uuid PRIMARY KEY REFERENCES source_versions(id) ON DELETE CASCADE,
            text               text NOT NULL,
            extractor          text NOT NULL,
            extractor_version  text NOT NULL DEFAULT '0.1.0',
            char_count         int NOT NULL,
            truncated          boolean NOT NULL DEFAULT false,
            frontmatter        jsonb NOT NULL DEFAULT '{}',
            links              text[] NOT NULL DEFAULT '{}',
            created_at         timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    _exec(
        """
        CREATE TABLE mirror_blobs (
            version_id  uuid PRIMARY KEY REFERENCES source_versions(id) ON DELETE CASCADE,
            media_type  text NOT NULL,
            size_bytes  bigint NOT NULL,
            data        bytea NOT NULL,
            created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    _exec(
        """
        CREATE TABLE chunks (
            id            uuid PRIMARY KEY,
            version_id    uuid NOT NULL REFERENCES source_versions(id) ON DELETE CASCADE,
            source_id     uuid NOT NULL REFERENCES sources(id),
            project_id    text NULL REFERENCES projects(id),
            ordinal       int NOT NULL CHECK (ordinal >= 0),
            text          text NOT NULL,
            text_hash     text NOT NULL,
            heading_path  text[] NOT NULL DEFAULT '{}',
            char_start    int NOT NULL,
            char_end      int NOT NULL,
            token_count   int NOT NULL,
            tsv           tsvector GENERATED ALWAYS AS (to_tsvector('english', text)) STORED,
            created_at    timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_chunks_offsets CHECK (char_end >= char_start)
        )
        """
    )
    _exec("CREATE UNIQUE INDEX uq_chunks_version_ordinal ON chunks (version_id, ordinal)")
    _exec("CREATE INDEX ix_chunks_text_hash ON chunks (text_hash)")
    _exec("CREATE INDEX ix_chunks_project ON chunks (project_id)")
    _exec("CREATE INDEX ix_chunks_source ON chunks (source_id)")
    _exec("CREATE INDEX ix_chunks_tsv ON chunks USING gin (tsv)")

    _exec(
        f"""
        CREATE TABLE embeddings (
            id           uuid PRIMARY KEY,
            object_type  text NOT NULL CHECK (object_type IN {OBJECT_TYPE}),
            object_id    uuid NOT NULL,
            text_hash    text NOT NULL,
            model_id     text NOT NULL REFERENCES embedding_models(id),
            dimension    int NOT NULL,
            vector       vector(384) NOT NULL,
            created_at   timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec(
        "CREATE UNIQUE INDEX uq_embeddings_object_model ON embeddings (object_type, object_id, model_id)"
    )
    _exec("CREATE UNIQUE INDEX uq_embeddings_hash_model ON embeddings (text_hash, model_id)")
    _exec(
        "CREATE INDEX ix_embeddings_vector ON embeddings "
        "USING hnsw (vector vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    _exec("CREATE INDEX ix_embeddings_object_type ON embeddings (object_type)")

    # --------------------------------------------------------------------------------------
    # 3. Episodes and knowledge
    # --------------------------------------------------------------------------------------
    _exec(
        f"""
        CREATE TABLE episodes (
            id                  uuid PRIMARY KEY,
            type                text NOT NULL CHECK (type IN {EPISODE_TYPE}),
            source_id           uuid NULL REFERENCES sources(id),
            version_id          uuid NULL REFERENCES source_versions(id),
            project_id          text NULL REFERENCES projects(id),
            title               text,
            section_path        text[] NOT NULL DEFAULT '{{}}',
            body                text,
            occurred_at         timestamptz,
            observed_at         timestamptz NOT NULL,
            status              text NOT NULL DEFAULT 'pending' CHECK (status IN {EPISODE_STATUS}),
            attempts            int NOT NULL DEFAULT 0,
            engine              text NULL CHECK (engine IN {ENGINE_KIND}),
            graph_episode_uuid  text,
            origin              text NOT NULL DEFAULT 'internal' CHECK (origin IN {ORIGIN}),
            origin_client       text,
            tier                smallint NOT NULL DEFAULT 2 CHECK (tier IN (0,1,2)),
            priority            int NOT NULL DEFAULT 100,
            error               text,
            ingestion_run_id    uuid NULL REFERENCES ingestion_runs(id),
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec(
        "CREATE UNIQUE INDEX uq_episodes_version_section ON episodes (version_id, section_path) "
        "WHERE version_id IS NOT NULL"
    )
    _exec(
        "CREATE INDEX ix_episodes_queue ON episodes (status, priority, created_at) "
        "WHERE status IN ('pending','queued','failed')"
    )
    _exec("CREATE INDEX ix_episodes_project ON episodes (project_id)")
    _exec("CREATE INDEX ix_episodes_source ON episodes (source_id)")
    _exec("CREATE INDEX ix_episodes_observed ON episodes (observed_at DESC)")

    _exec(
        f"""
        CREATE TABLE entities (
            id               uuid PRIMARY KEY,
            type             text NOT NULL CHECK (type IN {ENTITY_TYPE}),
            canonical_name   text NOT NULL,
            normalized_name  text NOT NULL,
            aliases          text[] NOT NULL DEFAULT '{{}}',
            project_id       text NULL REFERENCES projects(id),
            summary          text,
            status           text,
            merged_into_id   uuid NULL REFERENCES entities(id),
            confidence       real NOT NULL DEFAULT 1.0 CHECK (confidence BETWEEN 0 AND 1),
            engine           text NOT NULL DEFAULT 'deterministic' CHECK (engine IN {ENGINE_KIND}),
            first_seen_at    timestamptz NOT NULL DEFAULT now(),
            last_seen_at     timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    _exec(
        "CREATE UNIQUE INDEX uq_entities_type_normalized_project ON entities "
        "(type, normalized_name, coalesce(project_id, ''))"
    )
    _exec("CREATE INDEX ix_entities_trgm ON entities USING gin (normalized_name gin_trgm_ops)")
    _exec("CREATE INDEX ix_entities_project ON entities (project_id)")
    _exec(
        "CREATE INDEX ix_entities_merged ON entities (merged_into_id) "
        "WHERE merged_into_id IS NOT NULL"
    )

    _exec(
        """
        CREATE TABLE entity_mentions (
            id                    uuid PRIMARY KEY,
            entity_id             uuid NOT NULL REFERENCES entities(id),
            episode_id            uuid NOT NULL REFERENCES episodes(id),
            chunk_id              uuid NULL REFERENCES chunks(id),
            surface_form          text NOT NULL,
            char_start            int,
            char_end              int,
            confidence            real NOT NULL DEFAULT 1.0,
            -- [PROV] columns (plan section J); episode_id/confidence above are the same-named
            -- provenance columns and are declared once, per data-model.md §6.
            source_id             uuid NULL REFERENCES sources(id),
            source_uri            text,
            source_hash           text,
            source_version        uuid NULL REFERENCES source_versions(id),
            project_id            text NULL REFERENCES projects(id),
            device_id             text NOT NULL REFERENCES devices(id),
            observed_at           timestamptz NOT NULL,
            valid_from            timestamptz,
            valid_to              timestamptz,
            extraction_model_id   text NULL REFERENCES extraction_models(id),
            embedding_model_id    text NULL REFERENCES embedding_models(id),
            ingestion_run_id      uuid NULL REFERENCES ingestion_runs(id),
            heading_path          text[] NOT NULL DEFAULT '{}'
        )
        """
    )
    _exec("CREATE INDEX ix_entity_mentions_entity ON entity_mentions (entity_id)")
    _exec("CREATE INDEX ix_entity_mentions_episode ON entity_mentions (episode_id)")
    _exec("CREATE INDEX ix_entity_mentions_chunk ON entity_mentions (chunk_id)")

    _exec(
        f"""
        CREATE TABLE facts (
            id                          uuid PRIMARY KEY,
            subject_entity_id           uuid NOT NULL REFERENCES entities(id),
            predicate                   text NOT NULL CHECK (predicate IN {PREDICATE}),
            object_entity_id            uuid NULL REFERENCES entities(id),
            object_value                text NULL,
            statement                   text NOT NULL,
            valid_from                  timestamptz NOT NULL,
            valid_to                    timestamptz NULL,
            observed_at                 timestamptz NOT NULL,
            status                      text NOT NULL DEFAULT 'current' CHECK (status IN {FACT_STATUS}),
            source_status               text NOT NULL DEFAULT 'active' CHECK (source_status IN {SOURCE_STATUS}),
            invalidated_at              timestamptz,
            invalidated_by_episode_id   uuid NULL REFERENCES episodes(id),
            supersedes_fact_id          uuid NULL REFERENCES facts(id),
            confidence                  real NOT NULL DEFAULT 1.0,
            engine                      text NOT NULL DEFAULT 'deterministic' CHECK (engine IN {ENGINE_KIND}),
            project_id                  text NULL REFERENCES projects(id),
            -- [PROV] columns not already owned above.
            source_id                   uuid NULL REFERENCES sources(id),
            source_uri                  text,
            source_hash                 text,
            source_version              uuid NULL REFERENCES source_versions(id),
            device_id                   text NOT NULL REFERENCES devices(id),
            extraction_model_id         text NULL REFERENCES extraction_models(id),
            embedding_model_id          text NULL REFERENCES embedding_models(id),
            ingestion_run_id            uuid NULL REFERENCES ingestion_runs(id),
            episode_id                  uuid NULL REFERENCES episodes(id),
            CONSTRAINT ck_facts_object_xor CHECK ((object_entity_id IS NULL) <> (object_value IS NULL)),
            CONSTRAINT ck_facts_window CHECK (valid_to IS NULL OR valid_to >= valid_from)
        )
        """
    )
    _exec(
        f"CREATE UNIQUE INDEX uq_facts_functional_current ON facts (subject_entity_id, predicate) "
        f"WHERE valid_to IS NULL AND predicate IN {FUNCTIONAL_PREDICATES}"
    )
    _exec("CREATE INDEX ix_facts_subject ON facts (subject_entity_id)")
    _exec("CREATE INDEX ix_facts_object ON facts (object_entity_id)")
    _exec("CREATE INDEX ix_facts_predicate ON facts (predicate)")
    _exec("CREATE INDEX ix_facts_current ON facts (status) WHERE valid_to IS NULL")
    _exec("CREATE INDEX ix_facts_validity ON facts (valid_from, valid_to)")
    _exec("CREATE INDEX ix_facts_project ON facts (project_id)")
    _exec("CREATE INDEX ix_facts_episode ON facts (episode_id)")

    _exec(
        f"""
        CREATE TABLE knowledge_artifacts (
            id                  uuid PRIMARY KEY,
            type                text NOT NULL CHECK (type IN {ARTIFACT_TYPE}),
            title               text NOT NULL,
            body                text NOT NULL,
            structured          jsonb NOT NULL DEFAULT '{{}}',
            project_id          text NULL REFERENCES projects(id),
            current_status      text NOT NULL DEFAULT 'current' CHECK (current_status IN {ARTIFACT_STATUS}),
            valid_from          timestamptz NOT NULL,
            valid_to            timestamptz NULL,
            supersedes_id       uuid NULL REFERENCES knowledge_artifacts(id),
            superseded_by_id    uuid NULL REFERENCES knowledge_artifacts(id),
            confidence          real NOT NULL DEFAULT 1.0,
            evidence_quote      text,
            engine              text NOT NULL DEFAULT 'deterministic' CHECK (engine IN {ENGINE_KIND}),
            source_status       text NOT NULL DEFAULT 'active' CHECK (source_status IN {SOURCE_STATUS}),
            -- [PROV] columns not already owned above (knowledge_artifacts has no own observed_at).
            source_id           uuid NULL REFERENCES sources(id),
            source_uri          text,
            source_hash         text,
            source_version      uuid NULL REFERENCES source_versions(id),
            device_id           text NOT NULL REFERENCES devices(id),
            observed_at         timestamptz NOT NULL,
            extraction_model_id text NULL REFERENCES extraction_models(id),
            embedding_model_id  text NULL REFERENCES embedding_models(id),
            ingestion_run_id    uuid NULL REFERENCES ingestion_runs(id),
            episode_id          uuid NULL REFERENCES episodes(id),
            CONSTRAINT ck_artifacts_evidence_len CHECK (evidence_quote IS NULL OR length(evidence_quote) <= 300),
            CONSTRAINT ck_artifacts_window CHECK (valid_to IS NULL OR valid_to >= valid_from)
        )
        """
    )
    _exec("CREATE INDEX ix_artifacts_project_type ON knowledge_artifacts (project_id, type)")
    _exec(
        "CREATE INDEX ix_artifacts_current ON knowledge_artifacts (current_status) "
        "WHERE valid_to IS NULL"
    )
    _exec("CREATE INDEX ix_artifacts_validity ON knowledge_artifacts (valid_from DESC)")
    _exec("CREATE INDEX ix_artifacts_supersedes ON knowledge_artifacts (supersedes_id)")
    _exec("CREATE INDEX ix_artifacts_title_trgm ON knowledge_artifacts USING gin (title gin_trgm_ops)")
    _exec(
        "CREATE INDEX ix_artifacts_tsv ON knowledge_artifacts "
        "USING gin (to_tsvector('english', title || ' ' || body))"
    )

    _exec(
        f"""
        CREATE TABLE artifact_entities (
            artifact_id  uuid NOT NULL REFERENCES knowledge_artifacts(id),
            entity_id    uuid NOT NULL REFERENCES entities(id),
            role         text NOT NULL DEFAULT 'mentions' CHECK (role IN {ARTIFACT_ENTITY_ROLE}),
            PRIMARY KEY (artifact_id, entity_id, role)
        )
        """
    )
    _exec("CREATE INDEX ix_artifact_entities_entity ON artifact_entities (entity_id)")

    # --------------------------------------------------------------------------------------
    # 4. Operations and audit (ingestion_runs was created earlier)
    # --------------------------------------------------------------------------------------
    _exec(
        f"""
        CREATE TABLE ingestion_jobs (
            id           uuid PRIMARY KEY,
            run_id       uuid NOT NULL REFERENCES ingestion_runs(id),
            version_id   uuid NULL REFERENCES source_versions(id),
            source_id    uuid NULL REFERENCES sources(id),
            stage        text NOT NULL CHECK (stage IN {JOB_STAGE}),
            state        text NOT NULL DEFAULT 'pending' CHECK (state IN {JOB_STATE}),
            attempts     int NOT NULL DEFAULT 0,
            started_at   timestamptz,
            finished_at  timestamptz,
            duration_ms  int,
            error        text
        )
        """
    )
    _exec("CREATE UNIQUE INDEX uq_ingestion_jobs_version_stage ON ingestion_jobs (version_id, stage)")
    _exec(
        "CREATE INDEX ix_ingestion_jobs_state ON ingestion_jobs (state, stage) "
        "WHERE state IN ('pending','running')"
    )

    _exec(
        f"""
        CREATE TABLE source_events (
            id          uuid PRIMARY KEY,
            source_id   uuid NOT NULL REFERENCES sources(id),
            version_id  uuid NULL REFERENCES source_versions(id),
            event_type  text NOT NULL CHECK (event_type IN {SOURCE_EVENT_TYPE}),
            at          timestamptz NOT NULL DEFAULT now(),
            run_id      uuid NULL REFERENCES ingestion_runs(id),
            details     jsonb NOT NULL DEFAULT '{{}}'
        )
        """
    )
    _exec("CREATE INDEX ix_source_events_source_at ON source_events (source_id, at DESC)")
    _exec("CREATE INDEX ix_source_events_at ON source_events (at DESC)")

    _exec(
        """
        CREATE TABLE retrieval_logs (
            id                uuid PRIMARY KEY,
            at                timestamptz NOT NULL DEFAULT now(),
            query_text        text NOT NULL,
            query_hash        text NOT NULL,
            project_ids       text[] NOT NULL DEFAULT '{}',
            object_types      text[] NOT NULL DEFAULT '{}',
            as_of             timestamptz,
            since             timestamptz,
            "limit"           int NOT NULL DEFAULT 10,
            expand            boolean NOT NULL DEFAULT true,
            params            jsonb NOT NULL DEFAULT '{}',
            candidate_counts  jsonb NOT NULL DEFAULT '{}',
            result_ids        uuid[] NOT NULL DEFAULT '{}',
            latency_ms        int NOT NULL DEFAULT 0,
            client            text,
            warnings          text[] NOT NULL DEFAULT '{}'
        )
        """
    )
    _exec("CREATE INDEX ix_retrieval_logs_at ON retrieval_logs (at DESC)")
    _exec("CREATE INDEX ix_retrieval_logs_hash ON retrieval_logs (query_hash)")

    _exec(
        f"""
        CREATE TABLE mcp_audit_log (
            id            uuid PRIMARY KEY,
            at            timestamptz NOT NULL DEFAULT now(),
            tool          text NOT NULL,
            kind          text NOT NULL CHECK (kind IN {MCP_KIND}),
            client_id     text,
            arguments     jsonb NOT NULL DEFAULT '{{}}',
            confirmed     boolean NOT NULL DEFAULT false,
            allowed       boolean NOT NULL DEFAULT true,
            denied_reason text,
            result_ref    text,
            latency_ms    int
        )
        """
    )
    _exec("CREATE INDEX ix_mcp_audit_at ON mcp_audit_log (at DESC)")
    _exec("CREATE INDEX ix_mcp_audit_denied ON mcp_audit_log (allowed) WHERE NOT allowed")

    # --------------------------------------------------------------------------------------
    # provenance_v - one row per derived object (data-model.md §3)
    # --------------------------------------------------------------------------------------
    _exec(
        """
        CREATE VIEW provenance_v AS
        SELECT 'fact'::text AS object_type, f.id AS object_id, f.project_id, f.episode_id,
               f.source_id, f.source_uri, f.source_hash, f.source_version, f.device_id,
               f.observed_at, f.valid_from, f.valid_to, f.confidence,
               f.extraction_model_id, f.embedding_model_id, f.ingestion_run_id,
               s.uri AS current_source_uri, s.status AS source_status, sr.root_id, sr.label AS root_label,
               em.name AS extraction_model_name, em.digest AS extraction_model_digest,
               bm.name AS embedding_model_name, r.started_at AS run_started_at
        FROM facts f
        LEFT JOIN sources s            ON s.id  = f.source_id
        LEFT JOIN source_roots sr      ON sr.root_id = s.root_id
        LEFT JOIN extraction_models em ON em.id = f.extraction_model_id
        LEFT JOIN embedding_models bm  ON bm.id = f.embedding_model_id
        LEFT JOIN ingestion_runs r     ON r.id  = f.ingestion_run_id
        UNION ALL
        SELECT 'artifact'::text, a.id, a.project_id, a.episode_id,
               a.source_id, a.source_uri, a.source_hash, a.source_version, a.device_id,
               a.observed_at, a.valid_from, a.valid_to, a.confidence,
               a.extraction_model_id, a.embedding_model_id, a.ingestion_run_id,
               s.uri, s.status, sr.root_id, sr.label,
               em.name, em.digest,
               bm.name, r.started_at
        FROM knowledge_artifacts a
        LEFT JOIN sources s            ON s.id  = a.source_id
        LEFT JOIN source_roots sr      ON sr.root_id = s.root_id
        LEFT JOIN extraction_models em ON em.id = a.extraction_model_id
        LEFT JOIN embedding_models bm  ON bm.id = a.embedding_model_id
        LEFT JOIN ingestion_runs r     ON r.id  = a.ingestion_run_id
        UNION ALL
        SELECT 'entity_mention'::text, m.id, m.project_id, m.episode_id,
               m.source_id, m.source_uri, m.source_hash, m.source_version, m.device_id,
               m.observed_at, m.valid_from, m.valid_to, m.confidence,
               m.extraction_model_id, m.embedding_model_id, m.ingestion_run_id,
               s.uri, s.status, sr.root_id, sr.label,
               em.name, em.digest,
               bm.name, r.started_at
        FROM entity_mentions m
        LEFT JOIN sources s            ON s.id  = m.source_id
        LEFT JOIN source_roots sr      ON sr.root_id = s.root_id
        LEFT JOIN extraction_models em ON em.id = m.extraction_model_id
        LEFT JOIN embedding_models bm  ON bm.id = m.embedding_model_id
        LEFT JOIN ingestion_runs r     ON r.id  = m.ingestion_run_id
        """
    )

    # --------------------------------------------------------------------------------------
    # Seeds (idempotent: ON CONFLICT DO NOTHING so a re-run of this migration in a fresh
    # database is safe, and so `aimemory-ingest migrate` staying at head is a no-op).
    # --------------------------------------------------------------------------------------
    _exec(
        """
        INSERT INTO devices (id, label, os, notes) VALUES
            ('local-development-machine', 'Local development machine', 'Windows 11 Pro', NULL)
        ON CONFLICT (id) DO NOTHING
        """
    )
    _exec(
        """
        INSERT INTO embedding_models (id, name, dimension, revision, normalized, max_seq) VALUES
            ('minilm-l6-v2-384', 'sentence-transformers/all-MiniLM-L6-v2', 384,
             '1110a243fdf4706b3f48f1d95db1a4f5529b4d41', true, 256)
        ON CONFLICT (id) DO NOTHING
        """
    )
    _exec(
        """
        INSERT INTO extraction_models (id, provider, name, digest, parameters) VALUES
            ('deterministic:registry-v1', 'deterministic', 'registry', NULL, '{}'::jsonb),
            ('qwen3-4b', 'ollama', 'qwen3:4b', '359d7dd4bcda', '{}'::jsonb)
        ON CONFLICT (id) DO NOTHING
        """
    )


def downgrade() -> None:
    _exec("DROP VIEW IF EXISTS provenance_v")
    for table in (
        "mcp_audit_log",
        "retrieval_logs",
        "source_events",
        "ingestion_jobs",
        "artifact_entities",
        "knowledge_artifacts",
        "facts",
        "entity_mentions",
        "entities",
        "episodes",
        "embeddings",
        "chunks",
        "mirror_blobs",
        "source_text",
    ):
        _exec(f"DROP TABLE IF EXISTS {table} CASCADE")
    _exec("ALTER TABLE sources DROP CONSTRAINT IF EXISTS fk_sources_current_version")
    for table in (
        "source_versions",
        "sources",
        "ingestion_runs",
        "extraction_models",
        "embedding_models",
        "source_roots",
        "project_aliases",
        "projects",
        "devices",
    ):
        _exec(f"DROP TABLE IF EXISTS {table} CASCADE")
